#AvatarCreatures config

appa:
  # What item should be used to spawn in the Appa?
  # View https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for a list of items
  spawn-item: SADDLE
  # How fast should the Appa move? Range from 0.0-1.0
  movement-speed: 1.0
  # Should the player be automatically unmounted from the Appa if it/the player is hurt?
  unmount-when-appa-damaged: true
  unmount-when-player-damaged: true
  # Should the Appa despawn after the player unmounts?
  despawn-after-unmount: true
  # How long after unmounting should the Appa despawn? Time is in ticks (20 ticks = 1 second)
  despawn-time: 200

# AvatarCreatures can currently run through either a flat file using SQLite or a MySQL server.

#Options: flatfile or mysql
storage:
  storage-type: flatfile
  host: "localhost"
  port: 3306
  database: "minecraft?useSSL=false"
  username: "root"
  password: "password"





# DO NOT CHANGE THIS VALUE! This is used for internal purposes. Changing this may result in errors.
version: 2