#AvatarCreatures config

# AvatarCreatures can currently run through either a flat file using SQLite or a MySQL server.

appa:
  # What item should be used to spawn in the Appa?
  # View https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for a list of items
  spawn-item: SADDLE
  # Should the player be automatically unmounted from the Appa if it/the player is hurt?
  unmount-when-appa-damaged: true
  unmount-when-player-damaged: true

#Options: flatfile or mysql
storage:
 storagetype: flatfile
 host: "localhost"
 port: 3306
 database: "minecraft?useSSL=false"
 username: "root"
 password: "password"