#AvatarCreatures config

# Appa config
movement-steer-speed: 1

# AvatarCreatures can currently run through either a flat file using SQLite or a MySQL server.

#Options: flatfile or mysql
storage: flatfile
host: "localhost"
port: 3306
database: "minecraft?useSSL=false"
username: "root"
password: "password"