name: RavagerSaddle
version: ${project.version}
main: me.relavis.ravagersaddle.RavagerSaddle
api-version: 1.13
authors: [relavis]
depend: [ProtocolLib]
description: Right click with a saddle to ride a Ravager!
